=== rscarson/zarbans-grotto/schema/player.zarban.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/player.zarban.schema.json",
    "title": "ZARBAN_PLAYER",
    "description": "Describes the structure of the game of Zarban's Grotto",
    "additionalProperties": false,
    "required": ["entrypoint", "chapters", "choices", "inventory", "status"],
    "type": "object",
    
    "properties": {
        "$schema": {
            "type": "string"
        },
        "entrypoint": {
            "type": "string",
            "description": "Story ID to start new games on"
        },
        "chapters": {
            "type": "array",
            "description": "Set of JSON paths describing sections of the story",
            "items": {
                "type": "string",
                "description": "JSON path describing a part of the story"
            }
        },
        "choices": {
            "type": "string",
            "description": "JSON path describing the set of available game choices referenced in the story"
        },
        "inventory": {
            "type": "string",
            "description": "JSON path describing the set of available game items referenced in the story"
        },
        "status": {
            "type": "string",
            "description": "JSON path describing the set of available player status elements referenced in the story"
        }
    }
}

=== rscarson/zarbans-grotto/data/player.json
{
    "$schema": "../schema/player.zarban.schema.json",
    "entrypoint": "intro_cave1",
    
    "chapters": [
        "data/chapter1_cave.storyboard.json",
        "data/chapter2_footprints.storyboard.json",
        "data/chapter3_hunted.storyboard.json",
        "data/chapter4_jaccuse.storyboard.json"
    ],

    "choices": "data/player.choices.json",
    "inventory": "data/player.inventory.json",
    "status": "data/player.status.json"
}
